### ISSUE TITLE
Release a final version "2.0.0"

### ISSUE THREAD

**Issue by DieBauer** [kamon-io/kamon-akka-remote#25]
Currently there is only a RC available. Please release a final version of this dependency!

**Comment by ivantopo** [comment]
Hey @DieBauer, we actually released it already. Some time ago we merged all Akka-related instrumentation into the [kamon-akka](https://github.com/kamon-io/kamon-akka) repository. I just updated the README to point that out. 

Thanks for mentioning this and if you have any issues please stop by the [Gitter](https://gitter.im/kamon-io/Kamon) channel or the kamon-akka repo!
